clear;clc;
limit=268;
data=table2array(readtable('Dane/Gotowe/set1.csv'));
data2=table2array(readtable('Dane/Gotowe/set2.csv'));
data=data(1:limit,3:7);
data2=data2(1:limit,3:7);
output=transpose(data(2:limit-1,1));
data=[data(3:limit,2:5),data2(3:limit,:)];
input=transpose(data);
net = feedforwardnet(10);
net.divideParam.testRatio = 0.125;
net.divideParam.valRatio = 0.125;
net.trainParam.max_fail = 10;
net = train(net,input,output);
y=net(input(:,1));